spring.application.name=hanoi

spring.datasource.url=jdbc:postgresql://ep-patient-sound-at6a6ctt.c-9.us-east-1.aws.neon.tech:5432/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_QlxerjZG80fN

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
# Remove this line if present; Hibernate detects PostgreSQL automatically.
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect